name: Commando Shell

on:
  pull_request:
    types:
    - opened

jobs:
  commando:
    runs-on: ubuntu-22.04
    steps:
      - name: echo something
        run: |
          cat $GITHUB_ENV
          cat $GITHUB_OUTPUT
          echo "${{ job.status }}"
      - uses: actions/checkout@v3
      - run: |
          ls -la